trigger:
  - main

pool:
  vmImage: ubuntu-latest

variables:
  - group: school-management-secrets

jobs:
- job: Build_Deploy_API
  displayName: Build and Deploy .NET API
  steps:
  - task: UseDotNet@2
    displayName: Install .NET 10
    inputs:
      packageType: sdk
      version: 10.x
      includePreviewVersions: true

  - script: dotnet restore
    displayName: Restore packages
    workingDirectory: API/AngularDemoAPI/AngularDemoAPI

  - script: dotnet build --configuration Release
    displayName: Build API
    workingDirectory: API/AngularDemoAPI/AngularDemoAPI

  - script: dotnet publish --configuration Release --output $(Build.ArtifactStagingDirectory)/api
    displayName: Publish API
    workingDirectory: API/AngularDemoAPI/AngularDemoAPI

  - task: AzureWebApp@1
    displayName: Deploy API to Azure App Service
    inputs:
      azureSubscription: azure-service-connection
      appType: webAppLinux
      appName: school-mgmt-api
      package: $(Build.ArtifactStagingDirectory)/api

- job: Build_Deploy_UI
  displayName: Build and Deploy Angular UI
  steps:
  - task: NodeTool@0
    displayName: Install Node.js
    inputs:
      versionSpec: 20.x
  - script: npm install
    displayName: Install packages
    workingDirectory: UI/AngularDemo.Web
  - script: npm run build
    displayName: Build Angular
    workingDirectory: UI/AngularDemo.Web
  - task: AzureStaticWebApp@0
    displayName: Deploy UI to Static Web App
    inputs:
      app_location: UI/AngularDemo.Web
      output_location: dist/angular-demo-web/browser
      azure_static_web_apps_api_token: $(AZURE_STATIC_WEB_APPS_TOKEN)